version: '3.9'

services:
  postgres:
    image: postgres
    container_name: stock-exchange
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock-exchange-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma:
    image: node:16
    container_name: prisma
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npx prisma db push"
    depends_on:
      - postgres

volumes:
  postgres_data:
